name: Build Windows EXE

on:
  workflow_dispatch: # Ini akan memunculkan tombol 'Run' agar kita bisa menjalankannya manual kapan saja

jobs:
  build:
    name: Build Flutter Windows
    runs-on: windows-latest # Kita meminjam komputer Windows milik GitHub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3' # Menggunakan versi persis seperti di komputermu

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Artifact (Simpan Hasil)
        uses: actions/upload-artifact@v4
        with:
          name: SINDOMON-Windows-EXE
          # Ini adalah lokasi file .exe setelah berhasil di-compile
          path: build\windows\x64\runner\Release\*