name: Build Windows EXE

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Tarik Kodingan
        uses: actions/checkout@v4

      - name: Siapkan Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Ambil Package (Pub Get)
        run: flutter pub get

      - name: Build File EXE (Windows)
        run: flutter build windows --dart-define=API_BASE_URL=https://sindomon.cml-indonesia.com

      - name: Simpan Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-SINDOMON-Windows
          path: build\windows\x64\runner\Release